### ISSUE TITLE
'number' layout?

### ISSUE THREAD

**Issue by earboxer** [jjsullivan5196/wvkbd#19]
Sometimes things require floating point number inputs.

We should either have a 'number' layout, or have period on the 'dialer' layout.

My use-case is for the [scale_display.sh userscript](https://git.sr.ht/~anjan/sxmo-userscripts/tree/master/item/scripts/scale_display.sh).

**Comment by proycon** [comment]
Good idea, I think having a period on the dialer layout is probably
best.

**Comment by earboxer** [comment]
A comma was also requested for dialing with pauses https://todo.sr.ht/~mil/sxmo-tickets/457

**Comment by proycon** [comment]
I suppose we could split ``*`` into ``,`` and ``*``   and ``#`` into ``#`` and ``.`` ? Those keys are infrequent enough probably so no problem if they're slightly smaller

**Comment by proycon** [comment]
I guess we can close this as we have the specialpad layout for a while already?
