### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by AblatedSprocket** [jjsullivan5196/wvkbd#28]
I'm sure this is something simple but I don't have any background in C. I'm compiling this package from the AUR on my pinephone, and I'm getting an error in "drw.h" reporting "pango/pangocairo.h: No such file or directory".

I see the path to the file in question on my system is "/usr/include/pango-1.0/pango/pangocairo.h", I'm assuming the problem is the "pango-1.0". I tried adding pango-1.0 to the include line in drw.h, but it gets overwritten.

I'm probably just doing something stupid, I've spent a lot of time trying to get a functional keyboard on my pinephone and I am tired.

**Comment by proycon** [comment]
there's probably something wrong with your pkg-config not setting the right CFLAGS.

If you do  ``pkg-config --cflags pangocairo`` you should see a bunch of flags including ``-I/usr/include/pango-1.0``. This is what the Makefile runs to get these flags. You could add ``-I/usr/include/pango-1.0`` manually to the Makefile as a workaround.

**Comment by AblatedSprocket** [comment]
Thank you!
