### ISSUE TITLE
Single press produces multiple characters

### ISSUE THREAD

**Issue by EinarArnason** [jjsullivan5196/wvkbd#36]
I built wvkbd in Ubuntu 20.04 and started in sway. When using the keyboard in Chromium, one touch press produces double characters on screen. When I connected through VNC and pressed once, it produced 4 characters.

**Comment by proycon** [comment]
Hmm, that's odd indeed. When you hold touch, it will indeed repeat, but if it always produces doubles or four even then something is off indeed. Maybe the debug option (`-D`) reveals something more? You don't have the `-o` option enabled right? That could also such behaviour.

**Comment by Froggo8311** [comment]
I have the same issue. I don't have either `-o` or `-O` enabled. `-D` doesn't print any errors, or anything seemingly unordinary. I'm on a Microsoft Surface Go 2- it seems to be pretty consistent when I disconnect my hardware keyboard, reconnect it, and press keys with it before using wvkbd again.

**Comment by proycon** [comment]
This problem should be solved now with the above patch by @mojyack , please re-open if the problem persists.
