### ISSUE TITLE
No Super key on "main" keyboards

### ISSUE THREAD

**Issue by acidkewpie** [jjsullivan5196/wvkbd#37]
I added them into the default layouts myself, and i'm aware of the general encouraging to personalise layouts, but to not have the Super / Win key on the Landscape and Full layouts in the default code seems odd given how common it is to use as your WM modifer key.

**Comment by proycon** [comment]
In an sxmo context, we generally rely on other mechanisms to control the window manager (e.g. swipes elsewhere on the touchscreen, or even hardware buttons). So we basically didn't need it on the keyboard, and the small screen real estate on smartphones also makes it hard to fit a super button (you'd have to sacrifice another). There is a super key on the `special` layout though. And of course, you can indeed customize as you see fit!
