### ISSUE TITLE
--hidden flag seems to not work as of 0.14

### ISSUE THREAD

**Issue by bgkillas** [jjsullivan5196/wvkbd#41]
after updating and restarting, when bringing up the keyboard with the sigusr2 command it just popups a blank space where its meant to be, cant interact with it either

**Comment by proycon** [comment]
Thanks for reporting, this is a regression indeed. It seems it still works the first time SIGUSR2 it sent, but on any subsequent attempts, the keyboard doesn't render and the space is empty.

**Comment by proycon** [comment]
I proposed a patch that should fix this: https://lists.sr.ht/~mil/sxmo-devel/patches/44803

**Comment by proycon** [comment]
Fixed in master branch, pending release (v0.14.1)
