### ISSUE TITLE
is there a way to disable the keyboard?

### ISSUE THREAD

**Issue by MrMegaMango** [jjsullivan5196/wvkbd#49]
On a Raspberry Pi OS Bookworm

**Comment by proycon** [comment]
I'm not sure what you mean, if by disable you mean hide wvkbd, then yes,
send signal SIGUSR2 to hide and SIGUSR1 to show again (or SIGRTMIN to
toggle).

**Comment by kefabean** [comment]
On Raspberry Pi Bookworm I also didn't have any joy with the keyboard automatically appearing/hiding. This might be an issue with the version of Wayfire (0.7.4) I am using or the older version of wvkbd that is packaged with the OS (v12.1).

Right now, I'm resorting to using touch screen gestures to display/hide the keyboard, but would be interested to learn if there's anything I'm doing wrong.

**Comment by proycon** [comment]
> My understanding is that the wm/compositor should send these signals (eg. SIGUSR1/2, etc...) on entering a text field. 

No, any other process can send it (such as a gesture daemon like lisgd), but it's wvkbd specific and not an established mechanism. Compositors won't send it. What you're referring to, automatic showing/hiding based on text fields, is the wayland input method protocol, but wvkbd does not implement this yet.

**Comment by Draculagibus** [comment]
Hello,
So if I understand correctly, you need to use a daemon to toggle the SIGUSR1 / SIGUSR2 ? 
Or is there a way to configure them through wvkbd directly ?

I'm pretty sure a daemon is needed, but I don't find a lot of information on SIGUSR usage and I'm still learning linux

Thanks

**Comment by proycon** [comment]
From a terminal you can send the signal like:

hide: ``kill -USR1 $(pidof wvkbd-mobintl)``
show: ``kill -USR2 $(pidof wvkbd-mobintl)``
toggle: ``kill -34 $(pidof wvkbd-mobintl)``

You can't hide/show wvkbd from wvkbd itself no
