### ISSUE TITLE
Option to toggle the keyboard

### ISSUE THREAD

**Issue by AidanNotFunny** [jjsullivan5196/wvkbd#61]
I think it'd be a nice feature if there was an ability to toggle the keyboard on and off, as right now the process of opening and closing it is rather unintuitive. A solution could be just appending "--toggle" to the command to make it toggle. And no, sending SIGUSR1/2 is not a solution to this. That's quite clunky and not user friendly, we shouldn't have to install gesture daemons or do anything like that just to easily show and hide our keyboards.

**Comment by MrGamerDoesGames** [comment]
Update: Don't know if the dev is even still active or if they're going to add this, but I ended up writing a script that does the thing itself. Here it is for anyone interested, sorry for the amateurish scripting. I'm no programmer (even though I wish I was xD)

`if ps aux | grep [w]vkbd-mobintl | grep -v grep
then
    killall wvkbd-mobintl
else
    wvkbd-mobintl -L 240
fi`

I placed this in my /home under the name wvkbd-toggle.sh. You can just run the script and it toggles the keyboard. You can remove the -L parameter, that's just my personal settings. I personally use this with Waybar, I have a module that runs the script when clicked/tapped.

**Comment by rsJames-ttrpg** [comment]
Rather than using killall there is existing functionality for toggling the state.
```bash
#!/bin/bash

# Get the PID of wvkbd
WVKBD_PID=$(pgrep -x "wvkbd-mobintl")

# Check if wvkbd is running
if [ -z "$WVKBD_PID" ]; then
    # wvkbd is not running, so start it
    wvkbd
else
    # wvkbd is running, so toggle its visibility
    kill -SIGRTMIN "$WVKBD_PID"
fi
```
