### ISSUE TITLE
Question: I don't have SIGRTMIN so it seams. What signal to send for toggling?

### ISSUE THREAD

**Issue by FearlessSpiff** [jjsullivan5196/wvkbd#62]
Hi

I am on a Arch system and don't have SIGRTMIN. I can show and hide the kbd with USR2 and USR1 signal. But which to take for toggling? Could try all, but the first I did (TTIN) made the process suspend... :)

```
14:29:44 ~ $ kill -l
HUP INT QUIT ILL TRAP IOT BUS FPE KILL USR1 SEGV USR2 PIPE ALRM TERM STKFLT CHLD CONT STOP TSTP TTIN TTOU URG XCPU XFSZ VTALRM PROF WINCH POLL PWR SYS
```

Thanks!

**Comment by FearlessSpiff** [comment]
Lol. So it is so easy to just take the int number. For anybody reading this, just do `killall -34 wvkbd-mobintl` to toggle the keyboard

**Comment by proycon** [comment]
On Thu Jan 18, 2024 at 2:39 PM CET, FearlessSpiff wrote:
> Lol. So it is so easy to just take the int number. For anybody reading this, just do `killall -34 wvkbd-mobintl` to toggle the keyboard

This is the way ;)
