### ISSUE TITLE
Different language support?

### ISSUE THREAD

**Issue by FearlessSpiff** [jjsullivan5196/wvkbd#63]
I am using DE keyboard layout and Z, Y are reversed and all special chars are mapped wrong. Do I have to switch to US keyboard layout or is there a setting for this. Thanks!

**Comment by FearlessSpiff** [comment]
Yes. The first thing you described. I am on hyprland. Just tried to `loadkeys us` but this fails. Have to check why. Might this be the problem that wvkbd doesn't work as expected?

**Comment by proycon** [comment]
Okay, I'm on hyprland too, and it does seem like the keymap switching
wvkbd does work fine there. What I suspect is that you (or something you
are running) is somehow switching keymaps again by another means after
wvkbd has started? That would indeed lead to the two being out of sync.
Whilst wvkbd is running it should be the only one determining the
keymap, though this is not enforced in any way.

**Comment by FearlessSpiff** [comment]
I don't know why, but now it is working! I will have to make some more testing and observe it.

**Comment by freerig** [comment]
Actually it doesn't work for me either :( I use Hyprland on NixOS (super cool distro btw). All my env var are set to fr_FR.UTF-8, everything seems fine, but can't figure out how to have azerty. Maybe you should add a cli parameter (even if I manage to make it work  somehow).
