### ISSUE TITLE
Crash on first keypress in Hyprland > 0.36.0 (git master)

### ISSUE THREAD

**Issue by thefeiter** [jjsullivan5196/wvkbd#65]
Hi there,

after I built the binary and ran it it shows the keyboard as expected, but crashes as soon as I press a key.

The keystroke comes through.

Terminal output is:

```
./wvkbd-mobintl 
Initializing keyboard
Found 54 layouts
Found 2 layers
Resize 1920x120 1.000000, 55 layouts
xdg_surface@23: error 3: xdg_surface has never been configured
Wayland socket has been disconnected.
```

**Comment by AmirDahan** [comment]
Can confirm
Happens to me too
WAYLAND_DEBUG=1 log: [wvkbd.log](https://github.com/jjsullivan5196/wvkbd/files/14531107/wvkbd.log)

**Comment by jacekpoz** [comment]
for me, when launched manually with `--hidden`, then toggling it (using `SIGRTMIN`) it works as expected

then toggling it twice to hide and bring it back up, it crashes in the exact same way as described

crashes the first time after unhiding when it's launched through the hyprland config

**Comment by thefeiter** [comment]
v0.13 works for me

**Comment by proycon** [comment]
I'm puzzled. I'm can't seem to replicate this problem, but since three people reported it surely something must be wrong. I've tried wvkbd v0.14.4 (corresponds to git master at this point) on Hyprland 0.35.0, wayfire 0.8.0 and sway 1.9, and all seem to work fine, also after keypress. Only wayfire 0.7.x is known to have issues currently (https://github.com/jjsullivan5196/wvkbd/issues/52)

What compositor and version are you guys on? (and wvkbd version for completeness sake)

@jacekpoz I tried launching hidden and toggling as you described (on hyprland), but failed to reproduce it.

**Comment by stacyharper** [comment]
Could someone post the output with WAYLAND_DEBUG=1 please?

**Comment by proycon** [comment]
@stacyharper A log was provided by @AmirDahan already

**Comment by proycon** [comment]
Ok, I managed to replicate it now. I upgraded from Hyprland 0.35 to Hyprland 0.36 (didn't land in Arch yet so I was one version behind) and that indeed breaks wvkbd as described in this issue.

**Comment by proycon** [comment]
Correction, I'm on Hyprland git main, which is already ahead a bit of  0.36..  0.36 does seem to works fine..  But that implies that you all are running the hyprland development version as well?

**Comment by stacyharper** [comment]
The problems seems that the xdg popup surface is not configured correctly by the compositor. In the log provided, we can see the `xdg_surface@23.get_popup` request, while the error is `xdg_surface@23: error 3: xdg_surface has never been configured `. Also, we never receive the xdg_popup@configure event.

Reading the Wayland documentation, I don't see where we could have done something wrong. Does Hyprland works correctly with popups created for zwlr_layer_surfaces?

**Comment by vaxerski** [comment]
why do you gotta create the popup before the ls is mapped... ugh

**Comment by vaxerski** [comment]
I've fixed this, but fwiw, that's not good practice...

**Comment by proycon** [comment]
Thanks!

**Comment by jacekpoz** [comment]
updated hyprland to latest commit and wvkbd back to `wvkbd-0.14.3`, can confirm it works with no issues!

**Comment by AmirDahan** [comment]
Can confirm, It works fine now :+1:
