### ISSUE TITLE
wvkbd-0.14.3: Keyboard not visible under Sway for fullscreen clients

### ISSUE THREAD

**Issue by arbitrary-dev** [jjsullivan5196/wvkbd#73]
### Reproduction
1. Open `foot`
2. Open keyboard
3. Make `foot` fulscreen with <kbd>Super</kbd>+<kbd>f</kbd>
4. Now keyboard is not visible on this particular workspace
5. \+sxmo's context menus as well

**Comment by derkrasseleo** [comment]
I experience the same with a python application. It is opened in fullscreen and then opens a wvkbd process, which doesn't overlay the fullscreen application.

**Comment by proycon** [comment]
Found and implemented a fix for this now
