### ISSUE TITLE
Makefile target config.h is lacking dependency config.def.h

### ISSUE THREAD

**Issue by purewasa** [jjsullivan5196/wvkbd#77]
The  Makefile of current master branch has a target for config.h, that has no dependencies. Thus, config.h never gets updated,  when config.def.h changes.
Because of this, updating master from version 0.14.3 or 0.14.4 and compiling causes an error, since DEFAULT_ROUNDING is not yet present in old config.h

This can be fixed by adding the dependency "config.def.h"  to target "config.h".

I write this issue here, because I think a pull request would be oversized for that.

Kind regards,

purewasa

**Comment by proycon** [comment]
I see this dependency used to be there but was explicitly removed in commit 4ed89188 . 
The reason being that config.h may be modified by the user with custom
changes which we don't want to blindly overwrite with our defaults
(config.def.h). It indeed demands some action on part of the user to
consolidate the two versions (or just blindly do the cp) before upgrade.

This behaviour is also in line with what suckless tools (like dwm and
svkbd do).
