### ISSUE TITLE
Is it possible to use with KDE Kwin?

### ISSUE THREAD

**Issue by Xwang1976** [jjsullivan5196/wvkbd#78]
Hello,
Afaik KDE Kwin does not use wlroots, but claims to have a lot of it's functionality already implemented and I'm pretty sure to have read somewhere that it includes support for Wayland inputs protocol (I do not know which version). So the question is, can this keyboard be used in a Wayland KDE session?

**Comment by proycon** [comment]
As long as the KDE compositor implements the necessary wayland
protocols, which it probably does, it should just work I think. Just
give it a try.

**Comment by Xwang1976** [comment]
I've installed it using the AUR package, then I've run 

wvkbd-mobintl 

and it gives this messege and then closes:

virtual_keyboard_manager not available

Is it something else I should do? What than message means?

**Comment by MorsMortium** [comment]
https://wayland.app/protocols/virtual-keyboard-unstable-v1 Not implemented in KWin

**Comment by proycon** [comment]
Thanks, it seems neither KDE's kwin nor GNOME's mutter implement that protocol, so wvkbd won't work there unfortunately. wlroots-based compositors do implement it.
