### ISSUE TITLE
Compose messing up labels in upper case

### ISSUE THREAD

**Issue by 0x4261756D** [jjsullivan5196/wvkbd#8]
## Steps to reproduce: ##
* Press the shift key
* Press the cmp key
* Press any character key leading to a compose layout
* Press any composed character key
* keep typing
## Expected behaviour:
* The key labels are changed to lowercase (as the characters you type are lowercase)
* The shift key does not appear toggled anymore
## Observed behaviour:
* All labels are uppercase until they are pressed once, even though the typed characters are still lowercase
* The shift key still appears toggled

**Comment by jjsullivan5196** [comment]
Resolved by v0.7
